# This workflow will build a Java project with Gradle, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Gradle
on:
  workflow_dispatch:
  push:
    branches: [ "master" , "Jbran", "MLemus", "JCornejo", "RSandoval" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v3.6.0
        #Seteamos la version de Java
      - name: Set up JDK 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '21'
          distribution: 'temurin'
          #cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      # Instalar Google Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 120
          install-chromedriver: true
          install-dependencies: true
      #Limpiamos la cache de Gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        #Corremos los Test de Gradle
      - name: Run tests and collect coverage
        run: ./gradlew clean test
        #Enviamos los resultados a Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          # Use a particular Gradle version instead of the configured wrapper.
          gradle-version: 8.8

