name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      #Publicamos en GithubPackages
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3.6.0
        #Seteamos la version de Java
      - name: Set up JDK 21
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      # Instalar Google Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 120
          install-chromedriver: true
          install-dependencies: true
      #Limpiamos la cache de Gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish to Maven Central
        run: ./gradlew clean build javadocJar sourcesJar publish closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGN_KEY_PASS }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          DEPLOY_ACTIONS_GITHUB: ${{ secrets.DEPLOY_ACTIONS_GITHUB }}

